[package]
name = "lodestone-seer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodestone = { git = "https://github.com/djanatyn/lodestone", branch = "fix-tests" }
rusqlite = { version = "0.27" }
